### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ildarkhasanshin** [jbrooksuk/Intellitip#22]
plugin works but in console shows

Traceback (most recent call last):
  File "/home/ildar/.config/sublime-text-3/Packages/Intellitip/intellitip.py", line 15, in <lambda>
    sublime.set_timeout(lambda:self.run(view, 'activated'), 0)
  File "/home/ildar/.config/sublime-text-3/Packages/Intellitip/intellitip.py", line 22, in <lambda>
    sublime.set_timeout(lambda:self.run(view, 'selection_modified'), 0)
  File "/home/ildar/.config/sublime-text-3/Packages/Intellitip/intellitip.py", line 41, in run
    lang = self.getLang(view)
  File "/home/ildar/.config/sublime-text-3/Packages/Intellitip/intellitip.py", line 96, in getLang
    return re.match(".*/(.*?).sublime-syntax", view.settings().get("syntax")).group(1) #no match in predefined docs, return from syntax filename
AttributeError: 'NoneType' object has no attribute 'group'

st 3126
ubuntu 16.10

**Comment by ftndev** [comment]
Traceback (most recent call last):
  File "C:\Sublime3\Data\Packages\Intellitip\intellitip.py", line 15, in <lambda>
    sublime.set_timeout(lambda:self.run(view, 'activated'), 0)
  File "C:\Sublime3\Data\Packages\Intellitip\intellitip.py", line 41, in run
    lang = self.getLang(view)
  File "C:\Sublime3\Data\Packages\Intellitip\intellitip.py", line 96, in getLang
    return re.match(".*/(.*?).sublime-syntax", view.settings().get("syntax")).group(1) #no match in predefined docs, return from syntax filename
AttributeError: 'NoneType' object has no attribute 'group'

st 3126
winxp
